version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "sander.vandenberg"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: Bump:
      prefix-development: chore
      include: scope

  # Node.js dependencies for frontend
  - package-ecosystem: "npm"
    directory: "/elm-frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "sander.vandenberg"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: Bump:
      prefix-development: chore
      include: scope


  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "sander.vandenberg"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: Bump:
      prefix-development: chore
      include: scope
